name: Upload or Update Files in GCS

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  upload-update-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Get changed files
      id: changed-files
      run: |
        # List files added, modified, or renamed in the latest commit
        git diff --name-only --diff-filter=AMR HEAD^ HEAD > changed_files.txt
        cat changed_files.txt

    - name: Upload or update files in GCS
      if: success()
      run: |
        while IFS= read -r file; do
          echo "Processing $file..."
          if [ -f "$file" ]; then
            echo "Uploading or updating $file in GCS..."
            gsutil cp "$file" gs://github-bucket1/"$file"
          else
            echo "File $file does not exist locally. Skipping..."
          fi
        done < changed_files.txt
