name: Upload or Update .sh Files in GCS (Flatten Structure)

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  upload-update-sh-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Get changed .sh files
      id: changed-files
      run: |
        # Check if this is the first commit
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          echo "First commit detected. Listing all .sh files..."
          git ls-files '*.sh' > changed_files.txt
        else
          echo "Listing added, modified, or renamed .sh files in the latest commit..."
          git diff --name-only --diff-filter=AMR HEAD^ HEAD | grep '\.sh$' > changed_files.txt || true
        fi
        cat changed_files.txt

    - name: Upload or update .sh files in GCS (Flattened)
      if: success()
      run: |
        while IFS= read -r file; do
          echo "Processing $file..."
          if [ -f "$file" ]; then
            base_name=$(basename "$file")
            echo "Uploading $file as $base_name in GCS..."
            gsutil cp "$file" gs://cloudhustler/"$base_name"
          else
            echo "File $file does not exist locally. Skipping..."
          fi
        done < changed_files.txt
