name: Upload or Update Files

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  upload-update-sh-files:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '.sh') || 
      github.event.head_commit.modified | contains('.sh') || 
      github.event.head_commit.added | contains('.sh')  # Trigger only when .sh files are modified or added

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Get changed .sh files
      id: changed-files
      run: |
        # Check if this is the first commit
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          echo "First commit detected. Listing all .sh files..."
          git ls-files '*.sh' > changed_files.txt
        else
          echo "Listing added, modified, or renamed .sh files in the latest commit..."
          git diff --name-only --diff-filter=AMR HEAD^ HEAD | grep '\.sh$' > changed_files.txt || true
        fi
        cat changed_files.txt

    - name: Upload or update .sh files in GCS (Flattened)
      if: success()
      run: |
        while IFS= read -r file; do
          echo "Processing $file..."
          if [ -f "$file" ]; then
            base_name=$(basename "$file")
            echo "Uploading $file as $base_name in GCS..."
            gsutil cp "$file" gs://cloudhustler/"$base_name"
          else
            echo "File $file does not exist locally. Skipping..."
          fi
        done < changed_files.txt

  upload-md-files-to-public-repo:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '.md') || 
      github.event.head_commit.modified | contains('.md') || 
      github.event.head_commit.added | contains('.md')  # Trigger only when .md files are modified or added

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "Abhiraj-1604"
        git config --global user.email "abhirajrode2004@gmail.com"

    - name: Clone public repository
      run: |
        git clone https://github.com/Abhiraj-1604/cloudhustlerpublic.git
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}

    - name: Get changed .md files
      id: changed-md-files
      run: |
        # Check if this is the first commit
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          echo "First commit detected. Listing all .md files..."
          git ls-files '*.md' > changed_md_files.txt
        else
          echo "Listing added, modified, or renamed .md files in the latest commit..."
          git diff --name-only --diff-filter=AMR HEAD^ HEAD | grep '\.md$' > changed_md_files.txt || true
        fi
        cat changed_md_files.txt

    - name: Copy .md files to public repository
      run: |
        while IFS= read -r file; do
          echo "Copying $file to the public repository..."
          cp "$file" cloudhustlerpublic/
        done < changed_md_files.txt

    - name: Commit and push changes to public repository
      run: |
        cd cloudhustlerpublic
        git add .  # Add all changes
        git commit -m "Update .md files"
        git push https://Abhiraj-1604:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Abhiraj-1604/cloudhustlerpublic.git
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
